import type { ProjectConfig } from '../../config/schema'

interface IconItem { id: string; label: string; lucideName: string }

export function buildAppComponent(
  config: ProjectConfig,
  sidebarVariant: string,
  _activeIcons: IconItem[],
): string {
  const isHorizontal = sidebarVariant === 'horizontal'

  return `import Sidebar from './components/Sidebar'
import Chatbot from './components/Chatbot'

export default function App() {
  return (
    <div className="app${isHorizontal ? ' app--horizontal' : ''}">
      <Sidebar />
      <main className="main">
        <div className="main__header">
          <h1>${config.projectName}</h1>
          <p>Generated by Project Composer</p>
        </div>
        <div className="main__content">
          <Chatbot />
        </div>
      </main>
    </div>
  )
}
`
}
