import type { ProjectConfig } from '../../config/schema'

interface IconItem { id: string; label: string; lucideName: string }

export function buildAppComponent(
  config: ProjectConfig,
  sidebarVariant: string,
  _activeIcons: IconItem[],
): string {
  const isHorizontal = sidebarVariant === 'horizontal'
  const hasTopBar = config.sidebar.props.showProfile || config.sidebar.props.showNotifications

  const imports = [`import Sidebar from './components/Sidebar'`, `import Chatbot from './components/Chatbot'`]
  if (hasTopBar) {
    imports.unshift(`import { useState } from 'react'`)
    imports.push(`import TopBar from './components/TopBar'`)
  }

  const stateHook = hasTopBar ? `\n  const [sidebarOpen, setSidebarOpen] = useState(true)\n` : ''
  const topBarJsx = hasTopBar ? `\n          <TopBar sidebarOpen={sidebarOpen} onToggleSidebar={() => setSidebarOpen(!sidebarOpen)} />` : ''

  return `${imports.join('\n')}

export default function App() {${stateHook}
  return (
    <div className="app${isHorizontal ? ' app--horizontal' : ''}">
      <Sidebar />
      <main className="main">${topBarJsx}
        <div className="main__header">
          <h1>${config.projectName}</h1>
          <p>Generated by Project Composer</p>
        </div>
        <div className="main__content">
          <Chatbot />
        </div>
      </main>
    </div>
  )
}
`
}
