/**
 * GitHub integration — creates a repo on the user's account and pushes
 * the generated project files via the GitHub REST API.
 *
 * Auth: Personal Access Token stored in localStorage.
 * No backend needed — all calls go directly to api.github.com.
 */

import type { ProjectConfig } from '../config/schema'
import { buildProjectFiles } from './generate-project'

const GH_TOKEN_KEY = 'composer:github-token'
const API = 'https://api.github.com'

// ── Token management ─────────────────────────────────────────────────

export function getStoredToken(): string | null {
  return localStorage.getItem(GH_TOKEN_KEY)
}

export function storeToken(token: string): void {
  localStorage.setItem(GH_TOKEN_KEY, token)
}

export function clearToken(): void {
  localStorage.removeItem(GH_TOKEN_KEY)
}

// ── API helpers ──────────────────────────────────────────────────────

async function ghFetch(
  path: string,
  token: string,
  options: RequestInit = {},
): Promise<Response> {
  const res = await fetch(`${API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...((options.headers as Record<string, string>) ?? {}),
    },
  })
  return res
}

export async function validateToken(token: string): Promise<{ valid: boolean; username: string }> {
  const res = await ghFetch('/user', token)
  if (!res.ok) return { valid: false, username: '' }
  const data = await res.json()
  return { valid: true, username: data.login }
}

// ── Push to GitHub ───────────────────────────────────────────────────

export interface PushResult {
  success: boolean
  repoUrl?: string
  error?: string
}

export type PushProgress = (message: string) => void

export async function pushToGitHub(
  config: ProjectConfig,
  token: string,
  onProgress?: PushProgress,
): Promise<PushResult> {
  const log = onProgress ?? (() => {})

  try {
    // 1. Get the authenticated user
    log('Checking GitHub account...')
    const userRes = await ghFetch('/user', token)
    if (!userRes.ok) {
      return { success: false, error: 'Invalid GitHub token. Check your token and try again.' }
    }
    const user = await userRes.json()
    const owner: string = user.login

    // 2. Create the repository (auto_init creates a first commit so the Git Data API works)
    const repoName = config.projectName.replace(/[^a-zA-Z0-9_.-]/g, '-')
    log(`Creating repository ${owner}/${repoName}...`)

    const createRes = await ghFetch('/user/repos', token, {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        description: `Generated by Project Composer — ${config.themeId} theme`,
        private: false,
        auto_init: true,
      }),
    })

    if (!createRes.ok) {
      const err = await createRes.json()
      if (err.errors?.[0]?.message?.includes('already exists')) {
        return { success: false, error: `Repository "${repoName}" already exists on your account. Choose a different project name.` }
      }
      return { success: false, error: `Failed to create repository: ${err.message ?? createRes.statusText}` }
    }

    const repo = await createRes.json()
    const defaultBranch: string = repo.default_branch ?? 'main'

    // 3. Wait for the auto-init commit to be ready (GitHub is async)
    log('Waiting for repository initialization...')
    let parentCommitSha = ''
    for (let attempt = 0; attempt < 10; attempt++) {
      await delay(1000)
      const refRes = await ghFetch(`/repos/${owner}/${repoName}/git/ref/heads/${defaultBranch}`, token)
      if (refRes.ok) {
        const ref = await refRes.json()
        parentCommitSha = ref.object.sha
        break
      }
    }

    if (!parentCommitSha) {
      return { success: false, error: 'Repository created but initial commit not ready. Please try again.' }
    }

    // 4. Build all project files
    log('Generating project files...')
    const files = buildProjectFiles(config)

    // 5. Create blobs for each file
    log(`Uploading ${files.length} files...`)
    const blobShas: { path: string; sha: string }[] = []

    for (const file of files) {
      log(`  uploading ${file.path}`)
      const blobRes = await ghFetch(`/repos/${owner}/${repoName}/git/blobs`, token, {
        method: 'POST',
        body: JSON.stringify({
          content: btoa(unescape(encodeURIComponent(file.content))),
          encoding: 'base64',
        }),
      })

      if (!blobRes.ok) {
        const errBody = await blobRes.json().catch(() => ({}))
        return { success: false, error: `Failed to upload ${file.path}: ${errBody.message ?? blobRes.statusText}` }
      }

      const blob = await blobRes.json()
      blobShas.push({ path: file.path, sha: blob.sha })
    }

    // 6. Create a tree (replaces the auto-init README with our full project)
    log('Building file tree...')
    const treeRes = await ghFetch(`/repos/${owner}/${repoName}/git/trees`, token, {
      method: 'POST',
      body: JSON.stringify({
        tree: blobShas.map((b) => ({
          path: b.path,
          mode: '100644',
          type: 'blob',
          sha: b.sha,
        })),
      }),
    })

    if (!treeRes.ok) {
      const errBody = await treeRes.json().catch(() => ({}))
      return { success: false, error: `Failed to create file tree: ${errBody.message ?? treeRes.statusText}` }
    }

    const tree = await treeRes.json()

    // 7. Create a commit on top of the init commit
    log('Creating commit...')
    const commitRes = await ghFetch(`/repos/${owner}/${repoName}/git/commits`, token, {
      method: 'POST',
      body: JSON.stringify({
        message: 'Initial project from Project Composer',
        tree: tree.sha,
        parents: [parentCommitSha],
      }),
    })

    if (!commitRes.ok) {
      const errBody = await commitRes.json().catch(() => ({}))
      return { success: false, error: `Failed to create commit: ${errBody.message ?? commitRes.statusText}` }
    }

    const commit = await commitRes.json()

    // 8. Update the branch ref to point to our new commit
    log('Updating branch...')
    const updateRefRes = await ghFetch(`/repos/${owner}/${repoName}/git/refs/heads/${defaultBranch}`, token, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: true }),
    })

    if (!updateRefRes.ok) {
      const errBody = await updateRefRes.json().catch(() => ({}))
      return { success: false, error: `Failed to update branch: ${errBody.message ?? updateRefRes.statusText}` }
    }

    log('Done!')
    return { success: true, repoUrl: repo.html_url }
  } catch (err) {
    return { success: false, error: `Network error: ${err instanceof Error ? err.message : 'Unknown error'}` }
  }
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
