/**
 * GitHub integration — creates a repo on the user's account and pushes
 * the generated project files via the GitHub REST API.
 *
 * Auth: Personal Access Token stored in localStorage.
 * No backend needed — all calls go directly to api.github.com.
 */

import type { ProjectConfig } from '../config/schema'
import { buildProjectFiles } from './generate-project'

const GH_TOKEN_KEY = 'composer:github-token'
const API = 'https://api.github.com'

// ── Token management ─────────────────────────────────────────────────

export function getStoredToken(): string | null {
  return localStorage.getItem(GH_TOKEN_KEY)
}

export function storeToken(token: string): void {
  localStorage.setItem(GH_TOKEN_KEY, token)
}

export function clearToken(): void {
  localStorage.removeItem(GH_TOKEN_KEY)
}

// ── API helpers ──────────────────────────────────────────────────────

async function ghFetch(
  path: string,
  token: string,
  options: RequestInit = {},
): Promise<Response> {
  const res = await fetch(`${API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...((options.headers as Record<string, string>) ?? {}),
    },
  })
  return res
}

export async function validateToken(token: string): Promise<{ valid: boolean; username: string }> {
  const res = await ghFetch('/user', token)
  if (!res.ok) return { valid: false, username: '' }
  const data = await res.json()
  return { valid: true, username: data.login }
}

// ── Push to GitHub ───────────────────────────────────────────────────

export interface PushResult {
  success: boolean
  repoUrl?: string
  error?: string
}

export type PushProgress = (message: string) => void

export async function pushToGitHub(
  config: ProjectConfig,
  token: string,
  onProgress?: PushProgress,
): Promise<PushResult> {
  const log = onProgress ?? (() => {})

  try {
    // 1. Get the authenticated user
    log('Checking GitHub account...')
    const userRes = await ghFetch('/user', token)
    if (!userRes.ok) {
      return { success: false, error: 'Invalid GitHub token. Check your token and try again.' }
    }
    const user = await userRes.json()
    const owner: string = user.login

    // 2. Create the repository
    const repoName = config.projectName.replace(/[^a-zA-Z0-9_.-]/g, '-')
    log(`Creating repository ${owner}/${repoName}...`)

    const createRes = await ghFetch('/user/repos', token, {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        description: `Generated by Project Composer — ${config.themeId} theme`,
        private: false,
        auto_init: false,
      }),
    })

    if (!createRes.ok) {
      const err = await createRes.json()
      if (err.errors?.[0]?.message?.includes('already exists')) {
        return { success: false, error: `Repository "${repoName}" already exists on your account. Choose a different project name.` }
      }
      return { success: false, error: `Failed to create repository: ${err.message ?? createRes.statusText}` }
    }

    const repo = await createRes.json()

    // 3. Build all project files
    log('Generating project files...')
    const files = buildProjectFiles(config)

    // 4. Create blobs for each file
    log(`Uploading ${files.length} files...`)
    const blobShas: { path: string; sha: string }[] = []

    for (const file of files) {
      const blobRes = await ghFetch(`/repos/${owner}/${repoName}/git/blobs`, token, {
        method: 'POST',
        body: JSON.stringify({
          content: file.content,
          encoding: 'utf-8',
        }),
      })

      if (!blobRes.ok) {
        return { success: false, error: `Failed to upload ${file.path}` }
      }

      const blob = await blobRes.json()
      blobShas.push({ path: file.path, sha: blob.sha })
    }

    // 5. Create a tree
    log('Building file tree...')
    const treeRes = await ghFetch(`/repos/${owner}/${repoName}/git/trees`, token, {
      method: 'POST',
      body: JSON.stringify({
        tree: blobShas.map((b) => ({
          path: b.path,
          mode: '100644',
          type: 'blob',
          sha: b.sha,
        })),
      }),
    })

    if (!treeRes.ok) {
      return { success: false, error: 'Failed to create file tree.' }
    }

    const tree = await treeRes.json()

    // 6. Create a commit
    log('Creating commit...')
    const commitRes = await ghFetch(`/repos/${owner}/${repoName}/git/commits`, token, {
      method: 'POST',
      body: JSON.stringify({
        message: 'Initial commit from Project Composer',
        tree: tree.sha,
      }),
    })

    if (!commitRes.ok) {
      return { success: false, error: 'Failed to create commit.' }
    }

    const commit = await commitRes.json()

    // 7. Create the main branch ref pointing to that commit
    log('Setting up main branch...')
    const refRes = await ghFetch(`/repos/${owner}/${repoName}/git/refs`, token, {
      method: 'POST',
      body: JSON.stringify({
        ref: 'refs/heads/main',
        sha: commit.sha,
      }),
    })

    if (!refRes.ok) {
      return { success: false, error: 'Failed to create branch.' }
    }

    // 8. Update default branch to main
    await ghFetch(`/repos/${owner}/${repoName}`, token, {
      method: 'PATCH',
      body: JSON.stringify({ default_branch: 'main' }),
    })

    log('Done!')
    return { success: true, repoUrl: repo.html_url }
  } catch (err) {
    return { success: false, error: `Network error: ${err instanceof Error ? err.message : 'Unknown error'}` }
  }
}
